--Bài tập 1
SELECT DISTINCT CITY 
FROM STATION
WHERE ID%2=0
ORDER BY CITY

--Bài tập 2
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION

--Bài tập 3
SELECT CEILING(AVG(SALARY) - AVG(REPLACE(SALARY,'0','')) )
FROM EMPLOYEES

--Bài tập 4
SELECT ROUND(CAST(SUM(ITEM_COUNT*ORDER_OCCURRENCES) / SUM(ORDER_OCCURRENCES) AS DECIMAL),1) AS MEAN
FROM ITEMS_PER_ORDER

--Bài tập 5
SELECT CANDIDATE_ID
FROM CANDIDATES
WHERE SKILL IN ('PYTHON', 'TABLEAU', 'POSTGRESQL')
GROUP BY CANDIDATE_ID
HAVING COUNT(SKILL) >= 3
ORDER BY CANDIDATE_ID ASC

--Bài tập 6
SELECT USER_ID, DATE(MAX(POST_DATE))-DATE(MIN(POST_DATE)) 
FROM posts
WHERE POST_DATE>='2021-01-01' AND POST_DATE<='2022-01-01'
GROUP BY USER_ID
HAVING COUNT(POST_ID)>=2

--Bài tập 7
SELECT CARD_NAME, MAX(ISSUED_AMOUNT)-MIN(ISSUED_AMOUNT) AS MAX_MIN 
FROM monthly_cards_issued
GROUP BY CARD_NAME
ORDER BY MAX_MIN DESC

--Bài tập 8
SELECT MANUFACTURER, COUNT(PRODUCT_ID) AS DRUG_COUNT, ABS(SUM(COGS - TOTAL_SALES)) AS TOTAL_LOSS
FROM pharmacy_sales
WHERE TOTAL_SALES < COGS
GROUP BY MANUFACTURER
ORDER BY TOTAL_LOSS DESC

--Bài tập 9
SELECT ID, MOVIE, DESCRIPTION, RATING 
FROM CINEMA
WHERE ID%2=1 AND ID NOT IN (
    SELECT ID
    FROM CENIMA
    WHERE DESCRIPTION = 'BORING'
)
ORDER BY RATING DESC

--Bài tập 10
SELECT TEACHER_ID, COUNT(DISTINCT SUBJECT_ID) AS CNT
FROM TEACHER
GROUP BY TEACHER_ID
ORDER BY TEACHER_ID

--Bài tập 11
SELECT USER_ID, COUNT(FOLLOWER_ID) AS FOLLOWERS_COUNT
FROM FOLLOWERS
GROUP BY USER_ID
ORDER BY USER_ID ASC

--Bài tập 12
SELECT CLASS
FROM COURSES
GROUP BY CLASS
HAVING COUNT(STUDENT)>=5
