--Bài tập 1 
SELECT NAME
FROM STUDENTS 
WHERE MARKS>75 
ORDER BY RIGHT(NAME,3), ID ASC

--Bài tập 2
SELECT USER_ID, CONCAT(UPPER(LEFT(NAME,1)), LOWER(RIGHT(NAME,LENGTH(NAME)-1))) AS NAME
FROM USERS
ORDER BY USER_ID

--Bài tập 3
SELECT MANUFACTURER, '$'||ROUND(SUM(TOTAL_SALES)/1000000,0)||' '||'million' AS SALE
FROM pharmacy_sales
GROUP BY MANUFACTURER
ORDER BY SUM(TOTAL_SALES) DESC, MANUFACTURER

--Bài tập 4 
SELECT EXTRACT(MONTH FROM SUBMIT_DATE) AS MTH, PRODUCT_ID, ROUND(AVG(STARS),2) AS avg_stars
FROM reviews
GROUP BY EXTRACT(MONTH FROM SUBMIT_DATE), PRODUCT_ID
ORDER BY MTH, PRODUCT_ID

--Bài tập 5
SELECT SENDER_ID, COUNT(MESSAGE_ID) AS  MESSAGE_COUNT
FROM messages
WHERE EXTRACT(MONTH FROM SENT_DATE) = '8' AND EXTRACT(YEAR FROM SENT_DATE) = '2022'
GROUP BY SENDER_ID
ORDER BY MESSAGE_COUNT DESC
LIMIT 2

--Bài tập 6 
SELECT tweet_id
FROM Tweets
WHERE LENGTH(CONTENT)>15
ORDER BY tweet_id

--Bài tập 7
SELECT activity_date AS day , COUNT(DISTINCT USER_ID) AS active_users
FROM Activity
WHERE activity_date <= '2019-07-27' AND activity_date > '2019-06-27'
GROUP BY activity_date
HAVING COUNT(USER_ID) >=1
ORDER BY  activity_date

--Bài tập 8
select COUNT(ID) AS EMPLOYEE_COUNT
from employees
WHERE JOINING_DATE BETWEEN '2022-01-01 00:00:00' AND '2022-07-31 23:59:59'

--Bài tập 9
select POSITION('a' IN FIRST_NAME) AS PST
from worker
WHERE FIRST_NAME = 'Amitah'

--Bài tập 10 
select SUBSTRING(TITLE FROM POSITION('2' IN TITLE) FOR 4 )
from winemag_p2
WHERE country= 'Macedonia'
